pipeline{
 agent any
 stages{
   stage('Checkout'){
     steps{
        git branch: 'master', url:
'git@github.com:Ananya-raghav/dev_practice.git'
   }
  }
  stage('Hello'){
    steps{
      echo "hello from Jenkins Pipeline!"
     }
   }
  stage('Goodbye'){
    steps{
      echo "Pipeline finished sucessfully"
       }
     }
    }
   }
